package hb403.geoexplore.controllers;

import hb403.geoexplore.datatype.marker.ObservationMarker;
import hb403.geoexplore.datatype.marker.repository.ObservationRepository;
import hb403.geoexplore.util.GeometryUtil;

import java.util.*;

import io.swagger.v3.oas.annotations.Operation;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;


@RestController
public class ObservationController {

    @Autowired
    protected ObservationRepository obs_repo;


    // C of Crudl, adds observation to repo
    @Operation(summary = "Add a new observation to the database")
    @PostMapping(path = "geomap/observations")
    public @ResponseBody ObservationMarker saveObs(@RequestBody ObservationMarker observation) {
        if (observation != null) {
            observation.nullifyId();
            observation.enforceLocationIO();
            return this.obs_repo.save(observation);
        }
        return null;
    }

    // R of Crudl gets observation from repo
    @Operation(summary = "Get an observation from the database from its id")
    @GetMapping(path = "geomap/observations/{id}")
    public @ResponseBody ObservationMarker getObs(@PathVariable Long id) {
        if (id != null) {
            try {
                final ObservationMarker o = this.obs_repo.findById(id).get();
                o.enforceLocationTable();
                return o;
            } catch(Exception e) {
                // continue >>> (return null)
            }
        }
        return null;
    }

    // U of Crudl
    @Operation(summary = "Update an observation already in the database by its id")
    @PutMapping(path = "geomap/observations/{id}")
    public @ResponseBody ObservationMarker updateObs(@PathVariable Long id, @RequestBody ObservationMarker observation) {
        if (id != null && observation != null){
            observation.setId(id);
            observation.enforceLocationIO();
            return this.obs_repo.save(observation);
        }
        return null;
    }

    // D of Crudl
    @Operation(summary = "Delete an observation in the database by its id")
    @DeleteMapping(path = "geomap/observations/{id}")
    public @ResponseBody ObservationMarker deleteObs(@PathVariable Long id){
        if (id != null) {
            try {
                final ObservationMarker ref = this.getObs(id);
                this.obs_repo.deleteById(id);
                ref.enforceLocationTable();
                return ref;
            } catch(Exception e) {

            }
        }
        return null;
    }

    // L of Crudl
    @Operation(summary = "Get a list of all the observations in the database")
    @GetMapping(path = "geomap/observations")
    public List<ObservationMarker> getAllObs() {
        final List<ObservationMarker> obs = this.obs_repo.findAll();
        for (ObservationMarker o : obs){
            o.enforceLocationTable();
        }
        return obs;
    }


    /** Returns the list of events within the bounds generated by the provided WKT geometry string */
    @Operation(summary = "Get a list of the observations whose locations are bounded by the provided WKT geometry string")
	@GetMapping(path = "geomap/observations/within")
	public @ResponseBody List<ObservationMarker> getObservationsWithinBounds(@RequestBody String wkt_bounds_geom) {	// takes in 'well known text' for the bounding geometry --> may define special json formats for predefined bounds later
		try {
			final List<ObservationMarker> bounded = this.obs_repo.findWithin( GeometryUtil.getGeometry(wkt_bounds_geom) );
			// System.out.println("Recieved " + bounded.size() + " bounded events");
			for(ObservationMarker o : bounded) {
				o.enforceLocationTable();
			}
			return bounded;
		} catch(Exception e) {
			System.out.println("ObservationMarker.getObservationsWithinBounds(): Encountered exception! -- " + e.getMessage());
			// continue >>> (return null)
		}
		return null;
	}



    /** TODO:
     * - get marker creator (User) by marker id
     * - get marker tags (MarkerTag[]) by marker id
     * - append [NEW] marker tag to list, accessed by marker id
     * - append [EXISTING] marker tag to list, accessed by marker id and tag id
     * - append User to marker "listed users" by marker id and user id
     */


}
