package hb403.geoexplore.controllers;

import hb403.geoexplore.UserStorage.entity.User;
import hb403.geoexplore.UserStorage.repository.UserRepository;
import hb403.geoexplore.comments.CommentRepo.CommentRepository;
import hb403.geoexplore.comments.Entity.CommentEntity;
import hb403.geoexplore.datatype.MarkerTag;
import hb403.geoexplore.datatype.marker.EventMarker;
import hb403.geoexplore.datatype.marker.ObservationMarker;
import hb403.geoexplore.datatype.marker.ReportMarker;
import hb403.geoexplore.datatype.marker.repository.MarkerTagRepository;
import hb403.geoexplore.datatype.marker.repository.ReportRepository;
import hb403.geoexplore.util.GeometryUtil;

import java.util.*;

import io.swagger.v3.oas.annotations.Operation;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;


@RestController
public class ReportController {
	
	@Autowired
	protected ReportRepository reports_repo;
	@Autowired
    protected MarkerTagRepository tags_repo;
	@Autowired
	protected UserRepository users_repo;
	@Autowired
	protected CommentRepository commentRepository;


	/** [C]rudl - Add a new report to the database */
	@Operation(summary = "Add a new report to the database")
	@PostMapping(path = "geomap/reports")
	public @ResponseBody ReportMarker saveReport(@RequestBody ReportMarker report) {
		if(report != null) {
			report.nullifyId();
			report.enforceLocationIO();
			return this.reports_repo.save(report);
		}
		return null;
	}
	/** c[R]udl - Get a report from the database by it's id */
	@Operation(summary = "Get a report from the database from its id")
	@GetMapping(path = "geomap/reports/{id}")
	public @ResponseBody ReportMarker getReportById(@PathVariable Long id) {
		if(id != null) {
			try {
				final ReportMarker r = this.reports_repo.findById(id).get();
				r.enforceLocationTable();
				return r;
			} catch(Exception e) {
				// continue >>> (return null)
			}
		}
		return null;
	}
	/** cr[U]dl - Update a report already in the database by it's id */
	@Operation(summary = "Update a report already in the database by its id")
	@PutMapping(path = "geomap/reports/{id}")
	public @ResponseBody ReportMarker updateReportById(@PathVariable Long id, @RequestBody ReportMarker report) {
		if(id != null && report != null) {
			report.setId(id);
			report.enforceLocationIO();
			return this.reports_repo.save(report);
		}
		return null;
	}
	/** cru[D]l - Delete a report in the database by it's id */
	@Operation(summary = "Delete a report in the database by its id")
	@DeleteMapping(path = "geomap/reports/{id}")
	public @ResponseBody ReportMarker deleteReportById(@PathVariable Long id) {
		if(id != null) {
			try {
				final ReportMarker ref = this.getReportById(id);
				this.reports_repo.deleteById(id);
				/*if (ref.getComments()!= null) {
					List<CommentEntity> commentsToDelete = ref.getComments();
					commentsToDelete.forEach(comment -> {
						commentRepository.deleteById(comment.getId());
					});
				}*/
				ref.enforceLocationTable();
				return ref;
			} catch(Exception e) {
				// continue >>> (return null)
			}
		}
		return null;
	}

	/** crud[L] - Get a list of all the reports in the database */
	@Operation(summary = "Get a list of all the reports in the database")
	@GetMapping(path = "geomap/reports")
	public @ResponseBody List<ReportMarker> getAllReports() {
		final List<ReportMarker> reports = this.reports_repo.findAll();
		for(ReportMarker r : reports) {
			r.enforceLocationTable();
		}
		return reports;
	}



	/** Returns the list of reports within the bounds generated by the provided WKT geometry string */
	@Operation(summary = "Get the list of reports whose locations are bounded by the provided WKT geometry string")
	@GetMapping(path = "geomap/reports/within")
	public @ResponseBody List<ReportMarker> getReportsWithinBounds(@RequestBody String wkt_bounds_geom) {	// takes in 'well known text' for the bounding geometry --> may define special json formats for predefined bounds later
		try {
			final List<ReportMarker> bounded = this.reports_repo.findWithin( GeometryUtil.getGeometry(wkt_bounds_geom) );
			for(ReportMarker r : bounded) {
				r.enforceLocationTable();
			}
			return bounded;
		} catch(Exception e) {
			System.out.println("ReportMarker.getReportsWithinBounds(): Encountered exception! -- " + e.getMessage());
			// continue >>> (return null)
		}
		return null;
	}



	@Operation(summary = "Add a prexisting tag by its id to a marker by its id")
	@PostMapping(path = "geomap/reports/{id}/tags")
	public @ResponseBody ReportMarker addTagToMarkerById(@PathVariable Long id, @RequestBody Long tag_id) {
		if(id != null && tag_id != null) {
			try {
				final MarkerTag t = this.tags_repo.findById(tag_id).get();
				final ReportMarker m = this.reports_repo.findById(id).get();
				if(m.getTags().add(t)) {
					this.reports_repo.save(m);
					return m;
				}
			} catch(Exception e) {

			}
		}
		return null;
	}

	@Operation(summary = "Add a prexisting user by id as a confirmation to a marker by its id")
	@PostMapping(path = "geomap/reports/{id}/confirmations")
	public @ResponseBody ReportMarker addUserToConfirmedById(@PathVariable Long id, @RequestBody Long user_id) {
		if(id != null && user_id != null) {
			try {
				final ReportMarker m = this.reports_repo.findById(id).get();
				final User u = this.users_repo.findById(user_id).get();
				if(m.getConfirmed_by().add(u)) {
					this.reports_repo.save(m);
					return m;
				}
			} catch(Exception e) {

			}
		}
		return null;
	}



	/** TODO:
     * - get marker creator (User) by marker id
     * - get marker tags (MarkerTag[]) by marker id
     * - append [NEW] marker tag to list, accessed by marker id
     * - append [EXISTING] marker tag to list, accessed by marker id and tag id
     * - append User to marker "listed users" by marker id and user id
     */


}
